package com.lz.common.manager.file.model;

import lombok.Data;

@Data
public class Exif {

    private ExitDate AEBBracketValue; // 自动曝光补偿值
    private ExitDate AESetting; // 自动曝光设置
    private ExitDate AFAccelDecelTracking; // 自动对焦加速/减速跟踪
    private ExitDate AFAreaHeights; // 自动对焦区域高度
    private ExitDate AFAreaMode; // 自动对焦区域模式
    private ExitDate AFAreaSelectionMethod; // 自动对焦区域选择方法
    private ExitDate AFAreaWidths; // 自动对焦区域宽度
    private ExitDate AFAssistBeam; // 自动对焦辅助光
    private ExitDate AFCanonImageHeight; // AF影像高度
    private ExitDate AFCanonImageWidth; // AF影像宽度
    private ExitDate AFConfigTool; // AF配置工具
    private ExitDate AFImageHeight; // AF图像高度
    private ExitDate AFImageWidth; // AF图像宽度
    private ExitDate AFInfoSize; // AF信息大小
    private ExitDate AFMicroAdjMode; // 微调模式
    private ExitDate AFMicroAdjValue; // 微调值
    private ExitDate AFNumPoints; // 对焦点数量
    private ExitDate AFPoint; // 对焦点
    private ExitDate AFPointDisplayDuringFocus; // 对焦期间显示对焦点
    private ExitDate AFPointSwitching; // 对焦点切换
    private ExitDate AFPointUsed; // 使用的对焦点
    private ExitDate AFPointsInFocus; // 对焦中的点
    private ExitDate AFPointsSelected; // 已选的对焦点
    private ExitDate AFPointsUnusable; // 无法使用的对焦点
    private ExitDate AFStatusViewfinder; // 取景器中的对焦状态
    private ExitDate AFTrackingSensitivity; // 对焦追踪灵敏度
    private ExitDate AFValidPoints; // 有效对焦点
    private ExitDate AFXPositions; // 对焦点X坐标
    private ExitDate AFYPositions; // 对焦点Y坐标
    private ExitDate AIServoFirstImage; // AI伺服第一张图像
    private ExitDate AIServoSecondImage; // AI伺服第二张图像
    private ExitDate AmbienceSelection; // 环境选择
    private ExitDate ApertureValue; // 光圈值
    private ExitDate Artist; // 艺术家
    private ExitDate AutoAFPointSelEOSiTRAF; // 自动对焦点选择
    private ExitDate AutoExposureBracketing; // 自动曝光补偿
    private ExitDate AutoISO; // 自动ISO
    private ExitDate AutoLightingOptimizer; // 自动光照优化器
    private ExitDate AutoRotate; // 自动旋转
    private ExitDate BodySerialNumber; // 相机序列号
    private ExitDate BracketMode; // 曝光补偿模式
    private ExitDate BracketShotNumber; // 曝光补偿拍摄数量
    private ExitDate BracketValue; // 曝光补偿值
    private ExitDate BulbDuration; // 浴缸曝光持续时间
    private ExitDate ByteOrder; // 字节顺序
    private ExitDate CameraOwnerName; // 相机拥有者名称
    private ExitDate CameraTemperature; // 相机温度
    private ExitDate CameraType; // 相机类型
    private ExitDate ChromaticAberrationSetting; // 色差设置
    private ExitDate ColorSpace; // 色域
    private ExitDate ColorTemperature; // 色温
    private ExitDate ColorTone; // 色调
    private ExitDate ComponentsConfiguration; // 组件配置
    private ExitDate Compression; // 压缩类型
    private ExitDate Contrast; // 对比度
    private ExitDate ControlMode; // 控制模式
    private ExitDate Copyright; // 版权信息
    private ExitDate CustomPictureStyleFileName; // 自定义图像风格文件名
    private ExitDate CustomRendered; // 自定义渲染
    private ExitDate DateTime; // 日期时间
    private ExitDate DateTimeDigitized; // 数字化时间
    private ExitDate DateTimeOriginal; // 原始时间
    private ExitDate DigitalGain; // 数字增益
    private ExitDate DigitalZoom; // 数字变焦
    private ExitDate DisplayAperture; // 显示光圈
    private ExitDate DistortionCorrectionSetting; // 失真修正设置
    private ExitDate DriveMode; // 驱动模式
    private ExitDate EasyMode; // 简易模式
    private ExitDate ExifTag; // Exif标签
    private ExitDate ExifVersion; // Exif版本
    private ExitDate ExposureBiasValue; // 曝光偏差值
    private ExitDate ExposureCompensation; // 曝光补偿
    private ExitDate ExposureMode; // 曝光模式
    private ExitDate ExposureProgram; // 曝光程序
    private ExitDate ExposureTime; // 曝光时间
    private ExitDate FNumber; // 光圈值
    private ExitDate FileNumber; // 文件编号
    private ExitDate FileSize; // 文件大小
    private ExitDate FilterEffect; // 滤镜效果
    private ExitDate FirmwareVersion; // 固件版本
    private ExitDate Flash; // 闪光灯
    private ExitDate FlashActivity; // 闪光灯活动
    private ExitDate FlashBias; // 闪光灯偏差
    private ExitDate FlashDetails; // 闪光灯详情
    private ExitDate FlashExposureLock; // 闪光灯曝光锁定
    private ExitDate FlashGuideNumber; // 闪光灯引导数值
    private ExitDate FlashMode; // 闪光灯模式
    private ExitDate FlashOutput; // 闪光灯输出
    private ExitDate FlashpixVersion; // Flashpix版本
    private ExitDate FocalLength; // 焦距
    private ExitDate FocalPlaneResolutionUnit; // 焦平面分辨率单位
    private ExitDate FocalPlaneXResolution; // 焦平面X分辨率
    private ExitDate FocalPlaneYResolution; // 焦平面Y分辨率
    private ExitDate FocusContinuous; // 连续对焦
    private ExitDate FocusDistanceLower; // 最低焦距
    private ExitDate FocusDistanceUpper; // 最高焦距
    private ExitDate FocusMode; // 对焦模式
    private ExitDate FocusType; // 对焦类型
    private ExitDate Format; // 格式
    private ExitDate FrameCount; // 帧数
    private ExitDate GPSAltitudeRef; // GPS高度参考
    private ExitDate GPSMeasureMode; // GPS测量模式
    private ExitDate GPSSatellites; // GPS卫星数
    private ExitDate GPSStatus; // GPS状态
    private ExitDate GPSTag; // GPS标签
    private ExitDate GPSVersionID; // GPS版本ID
    private ExitDate HighISONoiseReduction; // 高ISO噪声减少
    private ExitDate HighlightTonePriority; // 高光优先
    private ExitDate ISOSpeed; // ISO速度
    private ExitDate ISOSpeedRatings; // ISO速度评级
    private ExitDate ImageHeight; // 图像高度
    private ExitDate ImageSize; // 图像大小
    private ExitDate ImageStabilization; // 图像稳定化
    private ExitDate ImageType; // 图像类型
    private ExitDate ImageWidth; // 图像宽度
    private ExitDate InitialAFPointInServo; // 初始伺服对焦点
    private ExitDate InternalSerialNumber; // 内部序列号
    private ExitDate InteroperabilityTag; // 互操作标签
    private ExitDate JPEGInterchangeFormat; // JPEG交换格式
    private ExitDate JPEGInterchangeFormatLength; // JPEG交换格式长度
    private ExitDate Lens; // 镜头
    private ExitDate LensDriveWhenAFImpossible; // 自动对焦无法驱动时镜头驱动
    private ExitDate LensModel; // 镜头型号
    private ExitDate LensSerialNumber; // 镜头序列号
    private ExitDate LensSpecification; // 镜头规格
    private ExitDate LensType; // 镜头类型
    private ExitDate LiveViewShooting; // 现场取景拍摄
    private ExitDate LongExposureNoiseReduction; // 长时间曝光噪声减少
    private ExitDate Macro; // 微距
    private ExitDate MacroMagnification; // 微距放大
    private ExitDate Make; // 制造商
    private ExitDate MakerNote; // 制造商备注
    private ExitDate ManualAFPointSelPattern; // 手动对焦点选择模式
    private ExitDate ManualFlashOutput; // 手动闪光灯输出
    private ExitDate MaxAperture; // 最大光圈
    private ExitDate MeasuredColor; // 测量颜色
    private ExitDate MeasuredEV; // 测量曝光值
    private ExitDate MeasuredEV2; // 测量曝光值2
    private ExitDate MeteringMode; // 测光模式
    private ExitDate MinAperture; // 最小光圈
    private ExitDate MinShutterSpeed; // 最小快门速度
    private ExitDate Model; // 型号
    private ExitDate ModelYear; // 型号年份
    private ExitDate NoiseReduction; // 噪声减少
    private ExitDate Orientation; // 定向
    private ExitDate OwnerName; // 拥有者名称
    private ExitDate PictureStyle; // 图片风格
    private ExitDate Quality; // 图像质量
    private ExitDate RawData; // 原始数据
    private ExitDate Saturation; // 饱和度
    private ExitDate SceneType; // 场景类型
    private ExitDate ShutterSpeed; // 快门速度
    private ExitDate Software; // 软件
    private ExitDate SoftwareVersion; // 软件版本
    private ExitDate SubjectDistance; // 物距
    private ExitDate SubjectDistanceRange; // 物距范围
    private ExitDate Thumbnail; // 缩略图
    private ExitDate TimeZone; // 时区
    private ExitDate WhiteBalance; // 白平衡

    @Data
    public static class ExitDate {
        private String value; // 日期值
    }
}
