/**
 * 创建图片扩图任务请求参数
 */
export interface CreatePictureOutPaintingTaskRequest {
  /** 图片 ID */
  pictureId: string

  /** 扩图参数 */
  parameters: CreateOutPaintingTaskParameters
}

/**
 * 扩图参数配置
 */
export interface CreateOutPaintingTaskParameters {
  /**
   * 可选，逆时针旋转角度，默认值 0，取值范围 [0, 359]
   */
  angle?: number

  /**
   * 可选，输出图像的宽高比，默认空字符串，不设置宽高比
   * 可选值：["", "1:1", "3:4", "4:3", "9:16", "16:9"]
   */
  outputRatio?: string

  /**
   * 可选，图像居中，在水平方向上按比例扩展，默认值 1.0，范围 [1.0, 3.0]
   */
  xScale?: number

  /**
   * 可选，图像居中，在垂直方向上按比例扩展，默认值 1.0，范围 [1.0, 3.0]
   */
  yScale?: number

  /**
   * 可选，在图像上方添加像素，默认值 0
   */
  topOffset?: number

  /**
   * 可选，在图像下方添加像素，默认值 0
   */
  bottomOffset?: number

  /**
   * 可选，在图像左侧添加像素，默认值 0
   */
  leftOffset?: number

  /**
   * 可选，在图像右侧添加像素，默认值 0
   */
  rightOffset?: number

  /**
   * 可选，开启图像最佳质量模式，默认值 false。若为 true，耗时会成倍增加
   */
  bestQuality?: boolean

  /**
   * 可选，限制模型生成的图像文件大小，默认值 true
   * - 单边长度 <= 10000：输出图像文件大小限制为 5MB 以下
   * - 单边长度 > 10000：输出图像文件大小限制为 10MB 以下
   */
  limitImageSize?: boolean

  /**
   * 可选，添加 "Generated by AI" 水印，默认值 true
   */
  addWatermark?: boolean
}

/**
 * 创建扩图任务的响应结果
 */
export interface CreateOutPaintingTaskResponse {
  /**
   * 表示任务的输出信息
   */
  output: CreateOutPaintingTaskResponseOutput

  /**
   * 接口错误码。
   * 接口成功请求不会返回该参数。
   */
  code: string

  /**
   * 接口错误信息。
   * 接口成功请求不会返回该参数。
   */
  message: string

  /**
   * 请求唯一标识。
   * 可用于请求明细溯源和问题排查。
   */
  requestId: string
}

/**
 * 扩图任务输出信息
 */
export interface CreateOutPaintingTaskResponseOutput {
  /**
   * 任务 ID
   */
  taskId: string

  /**
   * 任务状态
   * - PENDING：排队中
   * - RUNNING：处理中
   * - SUSPENDED：挂起
   * - SUCCEEDED：执行成功
   * - FAILED：执行失败
   * - UNKNOWN：任务不存在或状态未知
   */
  taskStatus: 'PENDING' | 'RUNNING' | 'SUSPENDED' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN'
}

/**
 * 查询扩图任务响应
 */
export interface GetOutPaintingTaskResponse {
  /**
   * 请求唯一标识
   */
  requestId: string

  /**
   * 输出信息
   */
  output?: GetOutPaintingTaskResponseOutput
}

/**
 * 任务输出信息
 */
export interface GetOutPaintingTaskResponseOutput {
  /**
   * 任务 ID
   */
  taskId: string

  /**
   * 任务状态
   * - PENDING：排队中
   * - RUNNING：处理中
   * - SUSPENDED：挂起
   * - SUCCEEDED：执行成功
   * - FAILED：执行失败
   * - UNKNOWN：任务不存在或状态未知
   */
  taskStatus: 'PENDING' | 'RUNNING' | 'SUSPENDED' | 'SUCCEEDED' | 'FAILED' | 'UNKNOWN'

  /**
   * 提交时间，格式：YYYY-MM-DD HH:mm:ss.SSS
   */
  submitTime: string

  /**
   * 调度时间，格式：YYYY-MM-DD HH:mm:ss.SSS
   */
  scheduledTime: string

  /**
   * 结束时间，格式：YYYY-MM-DD HH:mm:ss.SSS
   */
  endTime: string

  /**
   * 输出图像的 URL
   */
  outputImageUrl: string

  /**
   * 接口错误码（成功请求不会返回）
   */
  code?: string

  /**
   * 接口错误信息（成功请求不会返回）
   */
  message?: string

  /**
   * 任务指标信息
   */
  taskMetrics?: TaskMetrics
}

/**
 * 表示任务的统计信息
 */
export interface TaskMetrics {
  /**
   * 总任务数
   */
  total: number

  /**
   * 成功任务数
   */
  succeeded: number

  /**
   * 失败任务数
   */
  failed: number
}
