/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CoverUpload: typeof import('./src/components/CoverUpload.vue')['default']
    DictTag: typeof import('./src/components/DictTag.vue')['default']
    DirectionAwareHover: typeof import('./src/components/DirectionAwareHover.vue')['default']
    FancyImage: typeof import('./src/components/FancyImage.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MasonryImage: typeof import('./src/components/MasonryImage.vue')['default']
    PictureBatchUpload: typeof import('./src/components/PictureBatchUpload.vue')['default']
    PictureDownloadLogInfoTable: typeof import('./src/components/PictureDownloadLogInfoTable.vue')['default']
    PictureInfoList: typeof import('./src/components/PictureInfoList.vue')['default']
    PictureOutPainting: typeof import('./src/components/PictureOutPainting.vue')['default']
    PictureSearch: typeof import('./src/components/PictureSearch.vue')['default']
    PictureUpload: typeof import('./src/components/PictureUpload.vue')['default']
    PointsRechargeTable: typeof import('./src/components/PointsRechargeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    UComment: typeof import('undraw-ui')['UComment']
    UCommentNav: typeof import('undraw-ui')['UCommentNav']
    UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
    UFold: typeof import('undraw-ui')['UFold']
    UserBehaviorTable: typeof import('./src/components/UserBehaviorTable.vue')['default']
    UserloginLogTable: typeof import('./src/components/UserloginLogTable.vue')['default']
    UserPointsUsageLog: typeof import('./src/components/UserPointsUsageLog.vue')['default']
    UserViewInfoTable: typeof import('./src/components/UserViewInfoTable.vue')['default']
    VerticalFallLayout: typeof import('./src/components/VerticalFallLayout.vue')['default']
  }
}
