/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CoverUpload: typeof import('./src/components/CoverUpload.vue')['default']
    DirectionAwareHover: typeof import('./src/components/DirectionAwareHover.vue')['default']
    FancyImage: typeof import('./src/components/FancyImage.vue')['default']
    ImageOutPainting: typeof import('./src/components/ImageOutPainting.vue')['default']
    MasonryImage: typeof import('./src/components/MasonryImage.vue')['default']
    PictureEdit: typeof import('./src/components/PictureEdit.vue')['default']
    PictureInfoList: typeof import('./src/components/PictureInfoList.vue')['default']
    PictureOutPainting: typeof import('./src/components/PictureOutPainting.vue')['default']
    PictureUpload: typeof import('./src/components/PictureUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    UComment: typeof import('undraw-ui')['UComment']
    UCommentNav: typeof import('undraw-ui')['UCommentNav']
    UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
    UDivider: typeof import('undraw-ui')['UDivider']
    UFold: typeof import('undraw-ui')['UFold']
  }
}
